import{S as d,a as p,i}from"./assets/vendor-B_LUx5SO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g=new d(".gallery-link",{captionsData:"alt",aptionDelay:250}),l=document.querySelector(".gallery");function y(n){const t=n.map(({largeImageURL:o,webformatURL:a,tags:e,likes:r,views:s,comments:u,downloads:m})=>`<li class="gallery-item">
  <a class="gallery-link" href="${o}"><img src="${a}" alt="${e}" width="360" height="200" /></a>
  <div class="info">
        <p class="info-elem">Likes<br> ${r}</p>
        <p class="info-elem">Views<br> ${s}</p>
        <p class="info-elem">Comments<br> ${u}</p>
        <p class="info-elem">Downloads<br> ${m}</p>
  </div>
</li>`).join("");l.insertAdjacentHTML("beforeend",t),g.refresh()}function h(){l.innerHTML=""}const b="49396849-83bcb41d8b5c3c417310bffba",L="https://pixabay.com/api/";function S(n){return p(L,{params:{key:b,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data)}const c=document.querySelector(".form"),f=document.querySelector(".loader");c.addEventListener("submit",q);function q(n){n.preventDefault();const t=n.currentTarget.elements.searchText.value.trim();t&&(h(),P(),S(t).then(({hits:o})=>{if(o.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}y(o)}).catch(o=>{console.log(o),i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}).finally(()=>{c.reset(),$()}))}function P(){f.style.display="flex"}function $(){f.style.display="none"}
//# sourceMappingURL=index.js.map
