import{S as C,a as q,i as l}from"./assets/vendor-h_xsmXee.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v=new C(".gallery-link",{captionsData:"alt",aptionDelay:250}),y=document.querySelector(".gallery");function d(r){const t=r.map(({largeImageURL:s,webformatURL:n,tags:e,likes:o,views:i,comments:w,downloads:S})=>`<li class="gallery-item">
  <a class="gallery-link" href="${s}"><img src="${n}" alt="${e}" width="360" height="200" /></a>
  <div class="info">
        <p class="info-elem">Likes<br> ${o}</p>
        <p class="info-elem">Views<br> ${i}</p>
        <p class="info-elem">Comments<br> ${w}</p>
        <p class="info-elem">Downloads<br> ${S}</p>
  </div>
</li>`).join("");y.insertAdjacentHTML("beforeend",t),v.refresh()}function B(){y.innerHTML=""}const P="49396849-83bcb41d8b5c3c417310bffba",k="https://pixabay.com/api/";async function g(r,t=1,s){const{data:n}=await q(k,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}});return n}const p=document.querySelector(".form"),h=document.querySelector(".loader"),m=document.querySelector(".btn-more"),f=15;let a=1,c="";p.addEventListener("submit",R);m.addEventListener("click",$);async function R(r){if(r.preventDefault(),c=r.currentTarget.elements.searchText.value.trim(),u(),!!c){a=1,B(),b();try{const{hits:t,totalHits:s}=await g(c,a,f);if(t.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}d(t),x(),a*f>=s&&(l.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",position:"topRight"}),u())}catch{l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{p.reset(),L()}}}async function $(){b(),a+=1;try{const{hits:r,totalHits:t}=await g(c,a,f);d(r);const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),a*f>=t&&(u(),l.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",position:"topRight",backgroundColor:"#2ABB7C"}))}catch{l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{L()}}function b(){h.style.display="flex"}function L(){h.style.display="none"}function x(){m.style.display="block"}function u(){m.style.display="none"}
//# sourceMappingURL=index.js.map
